### ISSUE TITLE
Issue with IndieAuth.com?

### ISSUE THREAD

**Issue by RobinBoers** [aaronpk/indielogin.com#102]
Hi, I've been using IndieAuth on my site for a while now, but recently it stopped working. The strange thing is, only IndieLogin.com doesn't work. IndieAuth.com works fine.

Forexample: if I try to login to the indieweb wiki (via IndieLogin.com) I get this error:

![image](https://user-images.githubusercontent.com/60298132/224969634-f9f17d85-b34e-4348-a7b3-735bf403433a.png)

While logging into quill.p3k.io (via IndieAuth.com) works just fine: 

![image](https://user-images.githubusercontent.com/60298132/224969975-cfd96006-0b9e-4cbe-b193-ea8363e1e63f.png)

I think the problem is that IndieLogin.com doesn't support `authorization_endpoint` and `token_endpoint` anymore, in favour of `indieauth-metadata`.

However, IndieAuth.com doesn't seem to support `indieauth-metadata`?

**Comment by jasm1nii** [comment]
Chiming in to say that I am currently experiencing this same issue - I cannot login to the webmentions.io, which uses IndieLogin.com

**Comment by aaronpk** [comment]
hmm, indielogin.com definitely does still recognize `authorization_endpoint` and `token_endpoint`. @RobinBoers are you using CloudFlare or some CDN in front of your site? I tried to fetch your site with curl from the server that indielogin.com is running on and I got a verification interstitial page instead of your actual website:

> Please wait while your request is being verified...

So basically indielogin.com is not seeing your actual website, it's seeing a bot challenge screen.

@jasm1nii your problem seems to be entirely different. It's not clear to me from your comment which of your two websites linked from your github profile you are trying to use. If I try to log in to indielogin.com with `https://jasm1nii.xyz/` then I see the prompts I would expect. If I use `https://jasmineamalia.com/` then I see the error message, but that is what I would expect because I don't see any rel=me links on that website at all.

**Comment by jasm1nii** [comment]
Ah, I was trying to sign in with `https://jasm1nii.xyz/`, but adding `rel=authn` to the links I actually use for authentication (email and PGP) seems to have fixed the issue for me. This wasn't something I thought to add since other sites skipped over `https://jasmineamalia.com/` without fussing, which I also have linked in the home page of `https://jasm1nii.xyz/`.

**Comment by RobinBoers** [comment]
> So basically indielogin.com is not seeing your actual website, it's seeing a bot challenge screen.

Oh, yea that's probably the problem then. I'm gonna whitelist indielogin.com and try again. Thanks!

**Comment by aaronpk** [comment]
Looks like this has been resolved, feel free to comment if you're still having issues.

**Comment by jasm1nii** [comment]
Hi, this issue is happening again, despite IndieAuth working fine... not sure what's going on...

**Comment by jasm1nii** [comment]
Never mind, found the culprit. Turns out that I had mistakenly removed an Apache directive that ensured URLs were matched without the trailing slash.
