### ISSUE TITLE
Add Mastodon as a supported provider.

### ISSUE THREAD

**Issue by BenLubar** [aaronpk/indielogin.com#40]
The [FAQ](https://indieauth.com/faq#faq-how-to-be-added-to-supported-providers) on the old site seems to suggest that Mastodon would already be supported as a provider as it appears on the OmniAuth list, but neither `https://mastodon.lubar.me/@ben` nor `ben.lubar.me` allow Mastodon as a login option.

**Comment by aaronpk** [comment]
This project is written in PHP, not Ruby, so doesn't use OmniAuth.

Adding Mastodon support is unfortunately not a good long-term plan, since that implies I'd also have to add one-off support for the rest of the fediverse projects as well. 

Instead, it'd be easier for those projects to add IndieAuth support, so that they work natively as an IndieAuth server. If the service already supports OAuth 2, it's a relatively minor addition.

See https://aaronparecki.com/2018/07/07/7/oauth-for-the-open-web for some more background, and https://indieauth.spec.indieweb.org/ for the spec.
