### ISSUE TITLE
Indiewebify.me works fine but wiki indielogin fails

### ISSUE THREAD

**Issue by jevdemon** [aaronpk/indielogin.com#52]
Indiewebify.me indicates my indielogin is working correctly but the wiki login fails:

Indiewebify.me: 
  We found the following rel=me URLs on your site:
    https://twitter.com/jevdemon works perfectly
    https://keybase.io/jevdemon works perfectly
    https://github.com/jevdemon/ works perfectly

wiki (https://sso.indieweb.org/login?url=https%3A%2F%2Findieweb.org%2Fevents%252F2019-10-16-homebrew-website-club): 
Your IndieAuth server did not return a valid response. Below is the response from your server.
{
    "error": "Invalid auth code"
}

My site uses Known.  I'm still on version 0.9.2.

**Comment by aaronpk** [comment]
indielogin.com will use the built-in login of your site (ignoring all the rel=me links) since it sees the authorization endpoint from Known. This error is coming from Known. I don't remember the status of the IndieAuth plugin in that version, but you could ask in the Known chat or post an issue on their github.

**Comment by jevdemon** [comment]
I'll pursue this with Known and possibly fix it myself. Thanks
