### ISSUE TITLE
There was an SSL error connecting to...

### ISSUE THREAD

**Issue by TedTschopp** [aaronpk/indielogin.com#94]
I am getting the above error (There was an SSL error connecting to TedT.org) when trying to authenticate via IndieLogin.com using my personal webpage: TedT.org.  This use to work a couple years back when I first set all this up, and I don't know when it stopped working.  I only started debugging all this when Heroku went pay last month as I have to get my bridge between Github and Micrpub fixed.  My website's code is all in Github and uses Jekyll.  It's then hosted over on Cloudflare's CDN.  The SSL cert is from Cloudflare.  

Any ideas?  I don't see any documentation on SSL Errors on your site, and I don't see any mention of those errors in your code as well, so I think this is something that's surfacing up from a library that doesn't like the SSL cert that CloudFlare is issuing to give me HTTPS.  Again, any thoughts before I spend my EOY Vacation digging into it?

<img width="549" alt="Screenshot 2022-11-24 at 10 21 48 AM" src="https://user-images.githubusercontent.com/709984/203847444-4f6fed6e-163a-4b6e-89e6-5ec650825192.png">

I have the following set in the head of my website: 

```HTML
<link href="https://keybase.io/tedtschopp" rel="me">
<link href="https://github.com/TedTschopp/" rel="me">
<link href="https://www.linkedin.com/in/tedtschopp/" rel="me">
<link href="https://twitter.com/TedTschopp" rel="me">
<link href="https://www.facebook.com/ted.tschopp" rel="me">
<link href="https://plus.google.com/u/0/+TedTschopp" rel="me">
<link href="https://www.youtube.com/user/TedTschopp/" rel="me">
<link href="https://www.pinterest.com/TedTschopp/" rel="me">
<link href="https://www.reddit.com/user/tedtschopp/" rel="me">
<link href="https://www.instagram.com/tedtschopp/" rel="me">
<link href="https://www.quora.com/profile/Ted-Tschopp/" rel="me">
<link href="https://indieweb.org/User:Www.tedt.org/" rel="me">

<link rel="pingback" href="https://webmention.io/www.tedt.org/xmlrpc" />
<link rel="webmention" href="https://webmention.io/www.tedt.org/webmention" />

<link rel="authorization_endpoint" href="https://indieauth.com/auth">
<link rel="token_endpoint" href="https://tokens.indieauth.com/token">
<link href="https://micropub-to-github-for-ted.herokuapp.com/micropub/main" rel="micropub">

```

**Comment by aaronpk** [comment]
It looks like this error is coming from indieauth.com which is unable to fetch your site because of the TLS version. indieauth.com is unfortunately really old and I'm not planning on continuing to maintain it as a service for much longer. A longer term solution for you would be to replace indieauth.com with a different solution. I don't have a replacement service to offer just yet but you could look at the list here to see if one would work for you:

* https://indieweb.org/IndieAuth#IndieAuth_Providers 
* https://indieweb.org/IndieAuth#Server_Implementations

If you wanted to stick with indieauth.com for now, you'd need to figure out which TLS version to turn back on to allow it to make the request.

**Comment by TedTschopp** [comment]
This makes sense.  I do have all the settings turned on to ensure only the latest SSL goodness is accepted.  More to think about on how I modernize my website.

**Comment by ADIXGaminGTv** [comment]
@Youtube

**Comment by ADIXGaminGTv** [comment]
.github/contributing.md
